### PR TITLE
update binary

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by simoncozens** [comment]
It’s not that I don’t trust you, Georg, and I know it’s a binary in a repository, but binary pull requests to open source projects just *feel* like a security nightmare... :-) I’ll do a rebuild soon.

**Comment by schriftgestalt** [comment]
No problem. This is just an update to the binary you started with. But you can build it yourself now. I added the source to the binary to the [GlyphsSDK repo](https://github.com/schriftgestalt/GlyphsSDK/commit/88025e0d17804d4d26812ad6f375683156502c00). Make sure you build it with Xcode 12 to get a universal2 build for intel and arm support.

**Comment by simoncozens** [comment]
Ah, OK, I get this now. This won't be backwards compatible, right? So we need a new Glyphs 3 branch.

**Comment by schriftgestalt** [comment]
The binary should work in Glyphs 2+3.

**Pull request merged**
